routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'WelcomeController@index')->name('welcome');

Auth::routes();
Route::get('/redirect/{social}', 'SocialAuthController@redirect');
Route::get('/callback/{social}', 'SocialAuthController@callback');
Route::get('category/NewArrival', 'ProductController@getNewArrival');
Route::get('category/TopSell', 'ProductController@getTopSell');
Route::get('category/{group}/{name}', 'ProductController@getCategoryProduct');
Route::get('test/{id}', 'CategoryController@test');

Route::post('upload', 'UploadController@upload');

// Route to user profile
Route::get('profile', [
    'as' => 'profile',
    'uses' => 'ProfileController@getProfile',
]);
Route::post('sua_profile', [
    'as' => 'sua_profile',
    'uses' => 'ProfileController@postProfile',
]);
Route::get('edit_profile', [
    'as' => 'edit-profile-user',
    'uses' => 'ProfileController@getEditProfile',
]);

//product_details
Route::get('/product_details/{product_id}', 'ProductController@getProductDetails')->name('product_details')->middleware('product_status');
//shop_details
Route::get('/shop_details/{shop_product_id}', 'ShopDetailsController@getDetails')->name('shop_details');



//search
Route::post('search', 'ProductController@search')->name('search');
Route::get('search/{name}', 'ProductController@searchName')->name('search_name');

Route::post('/add_cart/{produc_id}', 'AddCartController@create')->name('add_cart');

Route::get('view_cart/{user_id}', 'ViewCartController@viewCart')->name('view_cart')->middleware('auth');
// Route to admin
Route::group(['prefix' => 'admin'], function(){
    Route::get('/', 'AdminController@getView')->middleware(['admin']);
    Route::group(['prefix' => 'category'],function(){
        //admin/category/cate_list
        Route::get('cate_list', 'AdminController@getList')->middleware(['admin']);
        Route::get('cate_list_child/{category_id}', 'AdminController@getListChild')->name('cate_list_child')->middleware(['admin']);
        Route::get('add', 'AdminController@getAdd')->middleware(['admin']);
        Route::post('add_cate', 'AdminController@postAdd')->name('add_cate')->middleware(['admin']);
        Route::get('cate_list/{id}/edit', 'AdminController@getEdit')->middleware(['admin']);
        Route::post('edit_category/{id}', 'AdminController@postEdit')->middleware(['admin']);
        Route::get('delete/{id}', 'AdminController@getDelete')->middleware(['admin']);
    });
    Route::group(['prefix' => 'product'],function(){
        //admin/product/product_list
        Route::get('product_list', 'AdminController@getProductList');
        Route::get('edit_product', 'AdminController@getEditProduct');
        Route::get('add_product', 'AdminController@getAddProduct');
        Route::post('add_product_post', 'AdminController@postAddProduct')->name('add_product_post');
        Route::get('product_list/{id}/edit_product', 'AdminController@getEditProduct');
        Route::post('edit_product_post/{id}', 'AdminController@postEditProduct');
        Route::get('delete/{id}', 'AdminController@getDeleteProduct');
        Route::get('category_child/{id}', 'AjaxController@getCategory');
    });
    Route::group(['prefix' => 'user'], function(){
        //admin/user/user_list
        Route::get('user_list', 'AdminController@getUserList');
        Route::get('admin_list', 'AdminController@getUserListAdmin');
        Route::get('customer_list', 'AdminController@getUserListCustomer');
        Route::get('setup_user/{id}', 'AdminController@getSetupUser');
        Route::get('delete/{id}', 'AdminController@getDeleteUser');
    });
    Route::group(['prefix' => 'order'], function(){
        //admin/order/order_list
        Route::get('order_list', 'AdminController@getOrderList');
        Route::get('order_today', 'AdminController@getOrderListToday');
        Route::get('order_doing', 'AdminController@getOrderListDoing');
        Route::get('order_done', 'AdminController@getOrderListDone');
        Route::get('orderdetail_list/{order_id}', 'AdminController@getDetailOrder')->name('orderdetail_list');
        Route::get('delete/{id}', 'AdminController@getDeleteOrder');
        Route::get('edit_order/{id}', 'AdminController@getEditOrder');
    });
    Route::group(['prefix' => 'ajax'], function(){

    });
});

Route::get('checkout_addresses/{order_id}', 'CheckOutController@get_checkout_addresses')->name('checkout_addresses')->middleware(['auth', 'cart']);

Route::post('checkout_addresses/{user_id}/{order_id}', 'CheckOutController@checkout_addresses' )->name('checkout_addresses_confirm');

Route::get('checkout_payment/{order_id}', function() {
    return view('checkout/checkout_payment');
})->name('checkout_payment');

Route::post('checkout_payment/{user_id}/{order_id}', 'CheckOutController@checkout_payment')->name('checkout_payment_confirm');

Route::get('checkout_confirm/{order_id}', 'CheckOutController@checkout_confirm')->name('checkout_confirm');

Route::post('checkout_confirm/{user_id}/{order_id}', 'CheckOutController@checkout_comfirm_done')->name('checkout_confirm_done');

//add product
Route::get('plus_product/{order_detail_id}', 'AddCartController@plus_product')->name('add_product');

Route::get('minus_product/{order_detail_id}', 'AddCartController@minus_product')->name('minus_product');
Route::get('delete_product/{order_detail_id}', 'AddCartController@delete_product')->name('delete_product');

//history
Route::get('view_cart/order/{id}', 'ViewCartController@viewCartWithId')->name('view_cart_id')->middleware(['auth','check_status_order']);

//show history orders
Route::get('history_orders', 'HistoryOrdersController@showHistory');

//comment
Route::resource('comment', 'CommentController');
Route::get('comment/{comment_id}/delete', [
        'as' => 'comment.delete',
        'uses' => 'CommentController@destroy',
    ]);
Route::post('/editComment', 'CommentController@updateComment');
Route::get('/replyComment', 'CommentController@replyComment');

//rate
Route::resource('rate', 'RateController', [
        'only' => ['store']
    ]);
//productShop
Route::get('product_shop/{shop_product_id}', 'ShopProductController@show_product')->name('product_shop');
//Contact
Route::get('contact', 'ContactController@getContact')->name('get_contact');
Route::post('contact', 'ContactController@postContact')->name('post_contact');

app/Http/Controllers/AdminController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Model;
use DB;
use App\Models\Product;
use App\Models\Category;
use App\Models\User;
use App\Models\ShopProduct;
use App\Models\Image;
use App\Models\Order;
use App\Models\OrderDetail;
use Illuminate\Support\Facades\File;
use Illuminate\Contracts\Filesystem\Filesystem;
use DateTime;


class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function getView()
    {
        return view('admin.category_master');
    }

    public function getList()
    {
        $category = Category::all();
        $categoryParent = Category::where('category_parent_id', NULL)->pluck('name', 'category_id')->toArray();
        $none['0'] = "None";
        $categoryParent = $none + $categoryParent;

        return view('admin.category', compact('categoryParent', 'category'));
    }

    public function getListChild($id)
    {
        $category = Category::where('category_parent_id', $id)->get();

        return view('admin.cate_child_list', ['category' => $category]);
    }

    public function getAdd()
    {
        $categoryParent = Category::where('category_parent_id', 0)->pluck('name', 'category_id')->toArray();
        $none['0'] = "None";
        $categoryParent = $none + $categoryParent;

        return view('admin.add_category', compact('categoryParent'));
    }

    public function postAdd(Request $request)
    {
        $this->validate($request,
            [
            'name' => 'required'
            ],
            [
            'name.requied' => 'Bạn chưa nhập category'
            ]);
        $category = new Category;
        $category->name = $request->name;
        $category->category_parent_id = $request->category_parent_id;
        $category->save();

        return redirect('admin/category/cate_list')->with('thongbao', 'add sucess !');
    }

    public function getEdit($id)
    {
        $category = Category::where('category_id', $id)->first();

        return view('admin.edit_category', ['category' => $category]);
    }

    public function postEdit(Request $request, $id)
    {
        $this->validate($request,
            [
                'name' => 'required|unique:categories,name'
            ],
            [
                'name.required' => 'Bạn Chưa nhập Category',
                'name.unique' => 'Category đã tồn tại'
            ]);
        $category =Category::where('category_id', $id)->first();
        $category->name = $request->name;
        $category->save();

        return redirect('admin/category/cate_list')->with('thongbao', 'Edit success !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function getDelete($id)
    {
        $category =  Category::find($id);
        $categoryChild = Category::where('category_parent_id', $id)->delete();
        $category->delete();

        return redirect('admin/category/cate_list')->with('thongbao1', 'Delete Success !');
    }

    public function getProductList()
    {
        $product = Product::where('status', 1)->get();
        return view('admin.product_list', ['product'=>$product]);
    }

    public function getAddProduct()
    {
        $category_parent = Category::where('category_parent_id', 0)->get();
        $category = Category::where('category_parent_id', $category_parent[0]['category_id'])->get();
        $shop_product = ShopProduct::all();
        return view('admin.add_product', ['category' => $category, 'shop_product' => $shop_product, 'category_parent' => $category_parent ]);
    }

    public function postAddProduct(Request $request)
    {
        $this->validate($request,
            [
            'name' => 'required',
            'unit_price' => 'numeric',
            'total_quanity' => 'numeric|min:1'
            ],
            [
            'name.requied' => trans('errors.product_name'),
            'unit_price.numeric' => trans('errors.unit_price'),
            'total_quanity' => trans('errors.total_quanity')
            ]);
        $product = new Product;
        $product->name = $request->name;
        $product->unit_price = $request->unit_price;
        $product->total_quanity = $request->total_quanity;
        $product->shop_product_id = $request->shop_product_id;
        $product->category_id = $request->category_id;
        $product->rate_count = 0 ;
        $product->top_product = $request->top_product;
        $product->information = $request->info_product;
        if(!$product->top_product) {
            $product->top_product = 100;
        }
        if(!$product->information) {
            $product->information = " ";
        }

        $product->save();
        $product->addToIndex();
        $category = Category::find($product->category_id);
        $shop_product = ShopProduct::find($product->shop_product_id);

        $file = $request->file('image_link');
        $name = time() . '_' . $file->getClientOriginalName();
        $file->move('assets/uploads', $name);
        $image = new Image;
        $image['link'] = $name;
        $image['product_id'] = $product->product_id;
        $image->save();
        $category->save();
        $shop_product->save();


        return redirect('admin/product/product_list')->with('thongbao', 'add sucess !');
    }

    public function getEditProduct($id)
    {
        $product = Product::find($id);

        return view('admin.edit_product', ['product'=>$product]);
    }

    public function postEditProduct(Request $request, $id)
    {
        $this->validate($request,
            [
            'name' => 'required',
            'unit_price' => 'numeric',
            'total_quanity' => 'numeric|min:1'
            ],
            [
            'name.requied' => trans('errors.product_name'),
            'unit_price.numeric' => trans('errors.unit_price'),
            'total_quanity' => trans('errors.total_quanity')
            ]);
        $product =Product::find($id);
        if ($request->name){
            $product->name = $request->name;
        }

        $product->unit_price = $request->unit_price;
        $product->total_quanity = $request->total_quanity;
        $product->top_product = $request->top_product;
        $product->information = $request->info_product;
        if(!$product->top_product) {
            $product->top_product = 100;
        }
        if(!$product->information) {
            $product->information = " ";
        }

        if ($request->image_link) {
            $file = $request->file('image_link');
            $name = time() . '_' . $file->getClientOriginalName();
            $file->move('assets/uploads', $name);
            // $image = Image::create([
            //     'link' => $name,
            //     'product_id' => $id,
            //     ]);
            $image = new Image;
            $image['link'] = $name;
            $image['product_id'] = $id;
            $image->save();

        }

        $product->save();
        $product->addToIndex();

        return redirect('admin/product/product_list')->with('thongbao', 'Edit success !');

    }

    public function getDeleteProduct($id)
    {
        DB::transaction(function() use ($id) {
            $product =  Product::find($id);
            $product->status = 0;
            $product->save();
        });

        return redirect('admin/product/product_list')->with('thongbao1', 'Delete Success !');
    }

    //Controller User
    public function getUserList()
    {
        $user = User::where('role', '<>', 3)->get();

        return view('admin.user_list', ['user'=>$user]);
    }

    public function getUserListAdmin()
    {
        $user = User::where('role',1)
            ->orwhere('role',2)
            ->get();

        return view('admin.admin_list', ['user'=>$user]);
    }
    public function getUserListCustomer()
    {
        $user = User::where('role', 0)->get();

        return view('admin.customer_list', ['user'=>$user]);
    }

    public function getDeleteUser($id)
    {
        $user =  User::find($id);
        $user->role = 3;
        $user->save();

        return redirect('admin/user/user_list')->with('thongbao1', 'Delete Success !');
    }

    public function getSetupUser($id)
    {
        $user =  User::find($id);
        if( $user->role == 0) {
            $user->role = 2;
        } elseif ($user->role == 2)
            $user->role = 0;
        $user->save();

        return redirect('admin/user/user_list');
    }

    //Controller Order
    public function getOrderList()
    {
        $order = Order::where('status', '<>', 2)->get();

        return view('admin.order_list', ['order'=>$order]);
    }
    public function getOrderListToday()
    {
        $date = new DateTime('today');
        $order = Order::where('created_at', '>', $date)->get();
        return view('admin.order_list', ['order'=>$order]);
    }
    public function getOrderListDoing()
    {
        $order = Order::where('status', 0)->get();

        return view('admin.order_list', ['order'=>$order]);
    }
    public function getOrderListDone()
    {
        $order = Order::where('status', 1)->get();

        return view('admin.order_list', ['order'=>$order]);
    }

    public function getDetailOrder($id)
    {
        $orderdetail = OrderDetail::where('order_id', $id)->get();
        $order = Order::where('order_id', $id)->get();

        return view('admin.detail_order', ['orderdetail' => $orderdetail, 'order' => $order]);
    }

    public function getDeleteOrder($id)
    {
        $order =  Order::find($id);
        $order->status = 2;
        $order->save();

        return redirect('admin/order/order_list')->with('thongbao1', 'Delete Success !');
    }
    public function getEditOrder($id)
    {
        $order =  Order::find($id);
        $order->status = 1;
        $order->save();

resources/views/admin/cate_child_list.blade.php
@extends('admin.category_master')
@section('category')
<div class="row">
    <!-- /.col-lg-12 -->
    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
            <tr align="center">
                <th style="text-align: center;">{{ trans('admin.id') }}</th>
                <th style="text-align: center;">{{ trans('admin.name') }}</th>
                <th style="text-align: center;">{{ trans('admin.edit') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($category as $cate)
            <tr class="odd gradeX" align="center">
                <td>{{ $cate->category_id }}</td>
                <td style="text-align: left;">{{ $cate->name }}</td>
                <td class="center">
                <a href="{{ action('AdminController@getEdit', $cate->category_id) }}" class="btn btn-warning" data-toggle="tooltip" title="Edit"><i class="fa fa-pencil fa-fw"></i></a>
                <a href="{{ action('AdminController@getDelete', $cate->category_id) }}" class="btn btn-danger" data-toggle="tooltip" title="Delete"><i class="fa fa-trash-o  fa-fw"></i></a></td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
<!-- /.row -->

@endsection

resources/views/admin/detail_order.blade.php
@extends('layouts.master')
@section('text-center')
    <section class="site-section site-section-light site-section-top themed-background-dark">
        <div class="container text-center">
            <h1 class="animation-slideDown"><strong>{{ trans('admin.explore_over') }}</strong></h1>
        </div>
    </section>
@endsection
@section('content')
    <section class="site-content site-section site-section2">
        <div id="wrapper">
            <!-- Navigation -->
            <div class="noti"><span class="notifi">{{ trans('admin.notification') }}</span> : <a href="#">{{ trans('admin.thongbao') }}</a></div>
            <nav class="navbar navbar-default navbar-static-top navbar2" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">{{ trans('admin.toggle_navigation') }}</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- <a class="navbar-brand" href="index.html">{{ trans('admin.admin_area') }} - <span class="admin_name">{{ Auth::user()->name }}</span></a> -->
                </div>
                <body class="news">

                <!-- /.navbar-header -->
                <!-- /.navbar-top-links -->
                <div class="navbar-default sidebar_admin" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li class="sidebar-search">
                                <div class="input-group custom-search-form">
                                    <input type="text" class="form-control" placeholder="Search...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </span>
                                </div>
                                <!-- /input-group -->
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-dashboard fa-fw"></i>{{ trans('admin.dashboard') }}</a>
                            </li>
                            <li>
                                <a href="{{ action('AdminController@getList') }}"><i class="fa fa-bar-chart-o fa-fw"></i>{{ trans('admin.category') }}<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="{{ action('AdminController@getList') }}">{{ trans('admin.list_category') }}</a>
                                    </li>
                                    <li>
                                        <a href="{{ action('AdminController@getAdd') }}">{{ trans('admin.add_category') }}</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <li>
                                <a href="{{ action('AdminController@getProductList') }}"><i class="fa fa-cube fa-fw"></i>{{ trans('admin.product') }}<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="{{ action('AdminController@getProductList') }}">{{ trans('admin.list_product') }}</a>
                                    </li>
                                    <li>
                                        <a href="{{ action('AdminController@getAddProduct') }}">{{ trans('admin.add_product') }}</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <li>
                                <a href="{{ action('AdminController@getUserList') }}"><i class="fa fa-users fa-fw"></i>{{ trans('admin.user') }}<span class="fa arrow"></span></a>
                            </li>
                            <li>
                                <a href="{{ action('AdminController@getOrderList') }}"><i class="fa fa-users fa-fw"></i>{{ trans('admin.order') }}<span class="fa arrow"></span></a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
            </nav>

            <!-- Page Content -->
            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        @if(session('thongbao1'))
                            <div class="alert alert-success">
                                {{ session('thongbao1') }}
                            </div>
                        @endif
                        <div class="row">
                            <div class="col-lg-12">
                                <h1 class="page-header header2">{{ trans('admin.order_detail') }}
                                    <small>{{ trans('admin.list') }}</small><span>  </span>
                                </h1>
                            </div>
                            <!-- /.col-lg-12 -->
                            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr align="center">
                                        <th>{{ trans('admin.product') }}</th>
                                        <th>{{ trans('admin.unit_price') }}</th>
                                        <th>{{ trans('admin.quanity') }}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($orderdetail as $orderdetail)
                                    <tr class="odd gradeX" align="center">
                                        <td class="center">{{ $orderdetail->product->name }}</td>
                                        <td class="center">{{ $orderdetail->unit_price }}</td>
                                        <td class="center">{{ $orderdetail->quality }}</td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.row -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /#page-wrapper -->
        </div>
    </section>
@endsection

resources/views/admin/order_master.blade.php
@extends('layouts.master')
@section('text-center')
    <section class="site-section site-section-light site-section-top themed-background-dark">
        <div class="container text-center">
            <h1 class="animation-slideDown"><strong>{{ trans('admin.explore_over') }}</strong></h1>
        </div>
    </section>
@endsection
@section('content')
    <section class="site-content site-section site-section2">
        <div id="wrapper">
            <!-- Navigation -->
            <div class="noti"><span class="notifi">{{ trans('admin.notification') }}</span> : <a href="#">{{ trans('admin.thongbao') }}</a></div>
            <nav class="navbar navbar-default navbar-static-top navbar2" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">{{ trans('admin.toggle_navigation') }}</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- <a class="navbar-brand" href="index.html">{{ trans('admin.admin_area') }} - <span class="admin_name">{{ Auth::user()->name }}</span></a> -->
                </div>
                <body class="news">

                <!-- /.navbar-header -->
                <!-- /.navbar-top-links -->
                <div class="navbar-default sidebar_admin" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li class="sidebar-search">
                                <div class="input-group custom-search-form">
                                    <input type="text" class="form-control" placeholder="Search...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </span>
                                </div>
                                <!-- /input-group -->
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-dashboard fa-fw"></i>{{ trans('admin.dashboard') }}</a>
                            </li>
                            <li>
                                <a href="{{ action('AdminController@getList') }}"><i class="fa fa-bar-chart-o fa-fw"></i>{{ trans('admin.category') }}<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="{{ action('AdminController@getList') }}">{{ trans('admin.list_category') }}</a>
                                    </li>
                                    <li>
                                        <a href="{{ action('AdminController@getAdd') }}">{{ trans('admin.add_category') }}</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <li>
                                <a href="{{ action('AdminController@getProductList') }}"><i class="fa fa-cube fa-fw"></i>{{ trans('admin.product') }}<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="{{ action('AdminController@getProductList') }}">{{ trans('admin.list_product') }}</a>
                                    </li>
                                    <li>
                                        <a href="{{ action('AdminController@getAddProduct') }}">{{ trans('admin.add_product') }}</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <li>
                                <a href="{{ action('AdminController@getUserList') }}"><i class="fa fa-users fa-fw"></i>{{ trans('admin.user') }}<span class="fa arrow"></span></a>
                            </li>
                            <li>
                                <a href="{{ action('AdminController@getOrderList') }}"><i class="fa fa-users fa-fw"></i>{{ trans('admin.order') }}<span class="fa arrow"></span></a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
            </nav>

            <!-- Page Content -->
            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header header2">{{ trans('admin.order') }}
                                <small>{{ trans('admin.list') }}</small>
                            </h1>
                        </div>
                        <div class="col-lg-12">
                            <div class="nav1">
                              <ul>
                                <li class="home"><a href="{{ action('AdminController@getOrderList') }}">All Order</a></li>
                                <li class="contact"><a href="{{ action('AdminController@getOrderListToday') }}">Order Today</a></li>
                                <li class="about"><a href="{{ action('AdminController@getOrderListDoing') }}">Order Doing</a></li>
                                <li class="contact"><a href="{{ action('AdminController@getOrderListDone') }}">Order Done</a></li>
                              </ul>
                            </div>
                        </div>
                        <!-- /.col-lg-12 -->
                        @if(session('thongbao1'))
                            <div class="alert alert-success">
                                {{ session('thongbao1') }}
                            </div>
                        @endif
                        @yield('order')
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /#page-wrapper -->
        </div>
    </section>
@endsection